# Connection to database

In [2]:
import pandas as pd
import plotly.express as px

df = pd.read_json("data.json")

data = df.to_dict(orient="records")

C:\Users\Travail\AppData\Local\Temp\ipykernel_46984\1111379459.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# Schools analytics

## Data request

In [3]:
normalized_df = pd.json_normalize(data, record_path='education', meta='profile_url')

# Group by "school" and count occurrences
grouped_schools = normalized_df.groupby('school').size().reset_index(name='count')

# Sort by count in descending order
sorted_schools = grouped_schools.sort_values(by='count', ascending=False)

## Displaying data

In [4]:

fig = px.bar(sorted_schools[:60], x="school", y="count", labels={'school':'Schools'})
fig.update_xaxes(showticklabels=False) # we hide x labels because it takes too much room. We can see school names by hovering bars
fig.show()

# Degrees analytics

## Data request

In [5]:
# Group by "school" and count occurrences
grouped_degrees = normalized_df.groupby('degree').size().reset_index(name='count')

# Sort by count in descending order
sorted_degrees = grouped_degrees.sort_values(by='count', ascending=False)

## Displaying data

In [6]:
fig = px.bar(sorted_degrees[:40], x="degree", y="count", labels={'degree':'Degree'})
fig.update_xaxes(showticklabels=False) # we hide x labels because it takes too much room. We can see school names by hovering bars
fig.show()

### Degrees of which schools?

In [7]:

# Filter rows where the degree is a Master
df_filtered = normalized_df[normalized_df['degree'].str.contains('Master|M\.Sc|MSc', case=False, na=False)]

# Group by school and degree and count occurrences
grouped_df = df_filtered.groupby(['school', 'degree']).size().reset_index(name='count')

# Sort by count in descending order
sorted_df = grouped_df.sort_values(by='count', ascending=False)

degrees_data = sorted_df.to_dict(orient="records")
degrees_data = [{ "Master": f"{edu['school']} | {edu['degree']}", "count": edu["count"] } for edu in degrees_data]

In [9]:
fig = px.bar(data[:20], x="Master", y="count")
fig.update_xaxes(showticklabels=False) # we hide x labels because it takes too much room. We can see school names by hovering bars
fig.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['profile_url', 'education', 'certifications'] but received: Master

# Research by school

In [10]:

df_filtered = normalized_df[
	normalized_df['school'].str.contains('Imperial College London', case=False, na=False)
]

df_filtered # A few Polytechs...

,school,degree,year,profile_url
219,Imperial College London,"Doctor of Philosophy - PhD, Mathematics",Oct 2018 - 2023,https://www.linkedin.com/in/killianmartinhorga...
220,Imperial College London,"Master in Statistics, Statistics",2015 - 2016,https://www.linkedin.com/in/killianmartinhorga...
439,Imperial College London,"B.Sc., Mathematics with Applied Mathematics / ...",1992 - 1995,https://www.linkedin.com/in/boris-schlittgen-b...
575,Imperial College London,"Master of Science - MS, Financial Mathematics",2018 - 2019,https://www.linkedin.com/in/francoisledain
719,Imperial College London,None,None,https://www.linkedin.com/in/julius-bonart-ba65...
760,Imperial College London,"Master of Science - MS, Statistics - Data Science",2020 - 2021,https://www.linkedin.com/in/robinmathelier
1080,Imperial College London,"Bachelor’s Degree, Physics",2013 - 2016,https://www.linkedin.com/in/darius-horban-8375...
1120,Imperial College London,"Doctor of Philosophy - PhD, Mathematics and St...",2017 - 2021,https://www.linkedin.com/in/valentin-courgeau-...
1123,Imperial College London,"Bachelor's degree, Mathematics",2015 - 2016,https://www.linkedin.com/in/valentin-courgeau-...
1355,Imperial College London,"Master of Engineering - MEng, Mechanical Engin...",2016 - 2020,https://www.linkedin.com/in/mark-gall-57178110a
1603,Imperial College London,"Master of Science - MS, Financial Mathematics",2017 - 2018,https://www.linkedin.com/in/mehdi-tomas-phd-aa...
1676,Imperial College London,"Master of Engineering - MEng, General Engineering",2019 - 2020,https://www.linkedin.com/in/yassineazizi
1684,Imperial College London,MSc Computing,Oct 2021 - Oct 2022,https://www.linkedin.com/in/julienpelegri
1692,Imperial College London,"Master of Science - MSc, Mathematics And Finance",2018 - 2019,https://www.linkedin.com/in/benyamin-azoulay-b...
1697,Imperial College London,"Doctor of Philosophy, Fluid dynamics",2013 - 2017,https://www.linkedin.com/in/yacine-debbabi
1944,Imperial College London,"Master of Science - MS, Machine Learning and D...",Oct 2021 - Oct 2023,https://www.linkedin.com/in/alex-barchenkov-57...
2101,Imperial College London,"Doctor of Philosophy (Ph.D.), Computational Fl...",2011 - 2014,https://www.linkedin.com/in/danjbarker
2175,Imperial College London,"PhD, Statistics",2013 - 2017,https://www.linkedin.com/in/vasileios-stampoul...
2176,Imperial College London,"MSc, Statistics",2012 - 2013,https://www.linkedin.com/in/vasileios-stampoul...
2207,Imperial College London,"Master’s Degree, Applied Mathematics",2014 - 2015,https://www.linkedin.com/in/justin-devito-3377...
2248,Imperial College London,"Bachelor of Science - BS, Theoretical and Math...",Sep 2019 - Jul 2022,https://www.linkedin.com/in/zhidong-zuo
2271,Imperial College London,PhD - Higher Order Tensor Decompositions for M...,2016 - 2020,https://www.linkedin.com/in/giuseppe-g-calvi-b...
2272,Imperial College London,MSc in Communications and Signal Processing,2015 - 2016,https://www.linkedin.com/in/giuseppe-g-calvi-b...
2317,Imperial College London,"Doctor of Philosophy - PhD, Computer Science",2015 - 2019,https://www.linkedin.com/in/radubaltean
2318,Imperial College London,"MEng, Computer Science",2009 - 2013,https://www.linkedin.com/in/radubaltean
2369,Imperial College London,"MSc, Applied Computational Science & Engineering",2021 - 2022,https://www.linkedin.com/in/nikhil-kumar-b5495...
2404,Imperial College London,BSc Mathematics,2022 - 2025,https://www.linkedin.com/in/yllinici
2428,Imperial College London,PhD in Mathematics,2014 - 2018,https://www.linkedin.com/in/maxime-morariu-pat...
2564,Imperial College London,"Master of Science (MSc), Mathematics and Finance",2018 - 2019,https://www.linkedin.com/in/rody-assaf-61b409152
2592,Imperial College London,"Master's degree, Engineering",None,https://www.linkedin.com/in/alex-zheng-b7b813273
2665,Imperial College London,Msc Maths&Finance,2019 - 2020,https://www.linkedin.com/in/cl%C3%A9a-morand-4...
2672,Imperial College London,"Master of Science (MSc), Mathematics and Finance",2017 - 2018,https://www.linkedin.com/in/stanley-meng-32427a9a
2709,Imperial College London,"Doctor of Philosophy - PhD, Computer Science",2018 - 2022,https://www.linkedin.com/in/cmcmeel
2715,Imperial College London,"Master's degree, MSc in Mathematics and Finance",Oct 2022 - Sep 2023,https://www.linkedin.com/in/christine-dong-666...
2758,Imperial College London,"Master of Science - MS, Mathematics and Finance",2020 - 2021,https://www.linkedin.com/in/ytereshchuk
2812,Imperial College London,"Visiting Student, Econometrics and Artificial ...",Feb 2023 - Aug 2023,https://www.linkedin.com/in/giuseppe-martucci-...
2864,Imperial College London,"Bachelor’s Degree, Mathematics and Management",1999 - 2002,https://www.linkedin.com/in/sid-ghoshal-44a741100
2883,Imperial College London,"MSc, Mathematics and Finance",2017 - 2018,https://www.linkedin.com/in/arthur-w-5a50a4108

# Certifications

In [11]:
normalized_df_certifications = pd.json_normalize(data, record_path='certifications', meta='profile_url')

## Overview

### Certification names

In [12]:
# Group by "school" and count occurrences
grouped_certifications = normalized_df_certifications.groupby('name').size().reset_index(name='count')

# Sort by count in descending order
sorted_certifications = grouped_certifications.sort_values(by='count', ascending=False)

In [13]:
fig = px.bar(sorted_certifications[:60], x="name", y="count", labels={'name':'Certification name'})
fig.update_xaxes(showticklabels=False) # we hide x labels because it takes too much room. We can see school names by hovering bars
fig.show()

### Certifications providers

In [14]:
# Group by "school" and count occurrences
grouped_certifications = normalized_df_certifications.groupby('institution').size().reset_index(name='count')

# Sort by count in descending order
sorted_certifications = grouped_certifications.sort_values(by='count', ascending=False)

In [20]:
fig = px.bar(sorted_certifications[:40], x="institution", y="count")
fig.update_xaxes(showticklabels=False) # we hide x labels because it takes too much room. We can see school names by hovering bars
fig.show()

## Specific certification research

In [19]:
normalized_df_certifications

filtered_certifs = normalized_df_certifications[
	normalized_df_certifications['institution'].str.contains('edX', case=False, na=False)
]

filtered_certifs

,name,institution,year,profile_url
174,edX Certificat Vérifié pour Circular Economy: ...,edX,Issued Jul 2022,https://www.linkedin.com/in/zriaa-imane
384,CS1156x: Learning From Data (Machine Learning),edX,Issued Jan 2017,https://www.linkedin.com/in/bouazzasaadeddine
474,edX Verified Certificate for Statistical Learning,edX,Issued Sep 2020,https://www.linkedin.com/in/sandeep-r-b44434149
500,edX Honor Code Certificate for Introduction to R,edX,Issued Jul 2015,https://www.linkedin.com/in/adityajha36
501,edX Honor Code Certificate for Supply Chain an...,edX,Issued Jul 2015,https://www.linkedin.com/in/adityajha36
505,edX Honor Code Certificate for Statistical Thi...,edX,None,https://www.linkedin.com/in/adityajha36
506,edX Honor Code Certificate for Statistical Thi...,edX,None,https://www.linkedin.com/in/adityajha36
507,edX Honor Code Certificate for Supply Chain De...,edX,None,https://www.linkedin.com/in/adityajha36
976,Exercising Leadership: Foundational Principles...,HarvardX - An Online Learning Initiative by Ha...,Issued May 2023,https://www.linkedin.com/in/yllinici
1006,MEPHI014x: Basic Concepts of International Nuc...,edX,Issued Apr 2020,https://www.linkedin.com/in/mario10m
1219,edX Honor Code Certificate for Introduction to...,edX,None,https://www.linkedin.com/in/jiayang-jerry-lyu-...
1233,edX Honor Code Certificate for Scalable Machin...,edX,None,https://www.linkedin.com/in/rhysjmartin
1241,edX Verified Certificate for Introduction to C...,edX,Issued Sep 2016,https://www.linkedin.com/in/arthur-w-5a50a4108